### ISSUE TITLE
rqt_bag --clock does not work

### ISSUE THREAD

**Issue by trainman419** [ros-visualization/rqt_common_plugins#244]
Playing back a bag file with --clock doesn't work. The clock is only published 2 or 3 times per second, and doesn't appear to increase linearly.

I suspect the issue here is that rospy is using the clock it's publishing and creating some kind of feedback look.

The GUI is also unresponsive while playing back my bag files; this may or may not be related to timer issues caused by using --clock.

**Comment by curranw** [comment]
I have the same issue, except rqt_bag skips a lot of tf packets. Even if the "Play all Messages" option is set. This seems like a serious problem, since it's difficult to visualize a bag if the robot is teleporting around.

If I use rosbag play instead of rqt_bag, everything runs fine.

Is there a current workaround for this?

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#3
