### ISSUE TITLE
rqt_console: TypeError signal has 2 argument(s) but 3 provided

### ISSUE THREAD

**Issue by peci1** [ros-visualization/rqt_common_plugins#414]
This week I started getting the following error when starting rqt_console on Indigo:

    TypeError: QAbstractItemModel.dataChanged[QModelIndex, QModelIndex] signal has 2 argument(s) but 3 provided
    Traceback (most recent call last):
      File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_console/message_proxy_model.py", line 118, in handle_highlight_filters_changed
        self.dataChanged.emit(self.index(0, 0), self.index(self.rowCount() - 1, self.columnCount() - 1), [])

The console doesn't work at all due to this error.

**Comment by DorianScholz** [comment]
The signature of dataChanged seems to have changed somewhere between Qt 4.8 and Qt 5.7:
http://doc.qt.io/qt-4.8/qabstractitemmodel.html#dataChanged
http://doc.qt.io/qt-5/qabstractitemmodel.html#dataChanged

The error is showing due to the change made by @dirk-thomas in:
https://github.com/ros-visualization/rqt_common_plugins/commit/5d8265c7ab9bc9d4232f15a6ada6e4623a4930ff

Not sure what the right move is here, maybe Dirk can elaborate on this change.

**Comment by dirk-thomas** [comment]
Thanks for reporting the regression. Can you please try and confirm if the fix from #416 makes it work for you again.

**Comment by DorianScholz** [comment]
works for me, thx.

**Comment by dirk-thomas** [comment]
Thanks for checking!
